version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "3030:3030"
    container_name: api

  web:
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    container_name: ui
